project:
  type: website
  output-dir: ../docs  

website:
  title: "YourName Portfolio"
  navbar:
    right:
      - text: "Home"
        href: "#home"
      - text: "About"
        href: "#about"
      - text: "Portfolio"
        href: "#portfolio"
  search: true  # Enable search functionality